name: Request access to playground-access-requests-repo
description: Paid access request for playground-access-requests-repo.
title: "Access request: playground-access-requests-repo"
labels: ["access-request"]

body:
  - type: markdown
    attributes:
      value: |
        <!-- entitlement_id: 63dda4ae-db81-41fc-b16d-4e590cd69d9b -->
        You are requesting paid access to **playground-access-requests-repo**.
        After submitting this issue, you will receive a payment link.

  - type: dropdown
    id: entitlement_id
    attributes:
      label: Entitlement ID
      description: This is selected automatically. Do not change it.
      options:
        - 63dda4ae-db81-41fc-b16d-4e590cd69d9b
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: Your email (optional)
      description: We'll only use this if we need to contact you about the request.
      placeholder: you@example.com
    validations:
      required: false
