name: Request access to playground-private-repo
description: Paid access request for playground-private-repo.
title: "Access request: playground-private-repo"
labels: ["access-request"]

body:
  - type: markdown
    attributes:
      value: |
        <!-- entitlement_id: 723770c2-8009-49a2-98fd-b357998424a7 -->
        You are requesting paid access to **playground-private-repo**.
        After submitting this issue, you will receive a payment link.

  - type: input
    id: contact
    attributes:
      label: Your email (optional)
      description: We'll only use this if we need to contact you about the request.
      placeholder: you@example.com
    validations:
      required: false
